### ISSUE TITLE
Collect load-balancer level metrics for providers

### ISSUE THREAD

**Issue by wolf31o2** [demeter-run/up#24]

**Comment by verbotenj** [comment]
Metrics:
- request rate
- latency
- data throughput

Aggregate metrics by subdomain, HTTP status, and upstream cluster

**Comment by verbotenj** [comment]
Use metrics in Prometheus.

Request rate:
cloudflared_tunnel_total_requests

Latency:
cloudflared_proxy_connect_latency_bucket
cloudflared_proxy_connect_latency_sum
cloudflared_proxy_connect_latency_count

Data Throughput:
quic_client_receive_bytes
quic_client_sent_bytes
