### ISSUE TITLE
Perform load testing of the environment

### ISSUE THREAD

**Issue by verbotenj** [demeter-run/up#79]
Load Tested:
- 50 Requests Per Second (RPS)
- 500 RPS
- 1000 RPS

Duration: Each load level was maintained for a minimum of 5 minutes.

Metrics Reported:

- Request Rate
- Latency
- Data Throughput

Analyze the reported metrics to identify any performance bottlenecks or issues at the respective RPS levels.

**Comment by verbotenj** [comment]
1. Testing 50 RPS for 5 minutes
Duration: 5 minutes = 300 seconds
RPS: 50
total number of requests: 50 * 300 = 15000

This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking foo.dmtr.host (be patient)
Completed 1500 requests
Completed 3000 requests
Completed 4500 requests
Completed 6000 requests
Completed 7500 requests
Completed 9000 requests
Completed 10500 requests
Completed 12000 requests
Completed 13500 requests
Completed 15000 requests
Finished 15000 requests

Server Software:        cloudflare
Server Hostname:        foo.dmtr.host
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-CHACHA20-POLY1305,2048,256
Server Temp Key:        ECDH X25519 253 bits
TLS Server Name:        foo.dmtr.host

Document Path:          /
Document Length:        35784 bytes

Concurrency Level:      50
Time taken for tests:   199.660 seconds
Complete requests:      15000
Failed requests:        0
Keep-Alive requests:    0
Total transferred:      548573313 bytes
HTML transferred:       536760000 bytes
Requests per second:    75.13 [#/sec] (mean)
Time per request:       665.534 [ms] (mean)
Time per request:       13.311 [ms] (mean, across all concurrent requests)
Transfer rate:          2683.14 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       27  174 288.7    111    4416
Processing:    55  487 417.3    349    5059
Waiting:       49  457 391.1    321    2377
Total:         89  661 533.4    558    6724

Percentage of the requests served within a certain time (ms)
  50%    558
  66%    814
  75%    930
  80%   1010
  90%   1224
  95%   1522
  98%   2297
  99%   2643
 100%   6724 (longest request)

**Comment by verbotenj** [comment]
Next test shows we got `Requests per second:    94.92 [#/sec] (mean)`

Were executed with
2 Kong instances

 ab -n 15000 -c 100 -k https://foo.dmtr.host/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking foo.dmtr.host (be patient)
Completed 1500 requests
Completed 3000 requests
Completed 4500 requests
Completed 6000 requests
Completed 7500 requests
Completed 9000 requests
Completed 10500 requests
Completed 12000 requests
Completed 13500 requests
Completed 15000 requests
Finished 15000 requests


Server Software:        cloudflare
Server Hostname:        foo.dmtr.host
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-CHACHA20-POLY1305,2048,256
Server Temp Key:        ECDH X25519 253 bits
TLS Server Name:        foo.dmtr.host

Document Path:          /
Document Length:        35784 bytes

Concurrency Level:      100
Time taken for tests:   158.030 seconds
Complete requests:      15000
Failed requests:        4
   (Connect: 0, Receive: 0, Length: 4, Exceptions: 0)
Keep-Alive requests:    0
Total transferred:      548545222 bytes
HTML transferred:       536729629 bytes
Requests per second:    94.92 [#/sec] (mean)
Time per request:       1053.536 [ms] (mean)
Time per request:       10.535 [ms] (mean, across all concurrent requests)
Transfer rate:          3389.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  364 540.2    166    8077
Processing:    54  582 561.7    451   15306
Waiting:       45  465 288.0    406    4362
Total:        105  946 861.9    718   15306

Percentage of the requests served within a certain time (ms)
  50%    718
  66%    895
  75%   1045
  80%   1163
  90%   1722
  95%   2498
  98%   3702
  99%   4697
 100%  15306 (longest request)

**Comment by verbotenj** [comment]
With more requests we didn't get response during 60s timeout

ab -n 15000 -c 200 -k -s 60 https://foo.dmtr.host/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking foo.dmtr.host (be patient)
Completed 1500 requests
Completed 3000 requests
Completed 4500 requests
Completed 6000 requests
Completed 7500 requests
SSL read failed (5) - closing connection
Completed 9000 requests
Completed 10500 requests
Completed 12000 requests
Completed 13500 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 14999 requests completed

**Comment by verbotenj** [comment]
1. Testing 50 RPS for 5 minutes

The following test results indicate that the server could handle a sustained load of around 72 requests per second
for the specific endpoint and test configuration used for 5 minutes. Which is more than required for the current test

```
wrk -t2 -c6 -d300s --timeout 30s https://test.dmtr.host/ping_provider_healthcheck
Running 5m test @ https://test.dmtr.host/ping_provider_healthcheck
  2 threads and 6 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    84.26ms   46.66ms 419.02ms   68.27%
    Req/Sec    36.31     12.60    70.00     54.72%
  21717 requests in 5.00m, 16.13MB read
Requests/sec:     72.37
Transfer/sec:     55.05KB
```

2. Testing 500 RPS for 5 minutes

The following test results indicate that the server could handle a sustained load of around 593 requests per second
for the specific endpoint and test configuration used for 5 minutes. Which is more than required for the current test

```
wrk -t8 -c50 -d300s --timeout 30s https://test.dmtr.host/ping_provider_healthcheck
Running 5m test @ https://test.dmtr.host/ping_provider_healthcheck
  8 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    82.21ms   46.04ms 739.66ms   70.53%
    Req/Sec    74.50     18.43   140.00     72.47%
  178059 requests in 5.00m, 132.27MB read
Requests/sec:    593.36
Transfer/sec:    451.35KB
```

3. Testing 1000 RPS for 5 minutes

The following test results indicate that the server could handle a sustained load of around 1161 requests per second
for the specific endpoint and test configuration used for 5 minutes. Which is more than required for the current test

```
wrk -t8 -c100 -d300s --timeout 30s https://test.dmtr.host/ping_provider_healthcheck
Running 5m test @ https://test.dmtr.host/ping_provider_healthcheck
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    85.36ms   61.49ms   1.32s    92.97%
    Req/Sec   146.30     28.05   240.00     70.36%
  348450 requests in 5.00m, 258.86MB read
Requests/sec:   1161.21
Transfer/sec:      0.86MB
```

4. Testing test website https://foo.dmtr.host (Not required, just for the experiment)

The website has been tested, and the results indicate that the server was able to handle a sustained
load of around 134 requests per second, but the latency was high at 361.89ms for the specific endpoint because the website is heavy with images that take long to load. We see that by the high latency and the amount of data transferred.

```
wrk -t8 -c50 -d300s --timeout 30s https://foo.dmtr.host
Running 5m test @ https://foo.dmtr.host
  8 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   361.89ms  182.78ms   1.69s    72.93%
    Req/Sec    17.86     10.18    60.00     71.26%
  40355 requests in 5.00m, 1.38GB read
Requests/sec:    134.47
Transfer/sec:      4.70MB
```

**Comment by wolf31o2** [comment]
These are with dev mode enabled and the cache disabled, so it's direct to the providers.
